site_name: My Tech Wiki

theme:
  name: material
  custom_dir: overrides

plugins_dir:
  - plugins

plugins:
  - search
  - roamlinks
  - backlinks

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite
  - toc:
      permalink: true
